# Generated by Django 4.1.3 on 2025-09-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0018_alter_student_discount'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainercourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainercourse',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_courses', to='example.batch'),
        ),
        migrations.AlterUniqueTogether(
            name='trainercourse',
            unique_together={('trainer', 'course', 'batch')},
        ),
    ]
