# Generated by Django 4.1.3 on 2025-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_trainercourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainercourse',
            name='schedule',
            field=models.CharField(blank=True, choices=[('weekend', 'Weekend'), ('weekdays', 'Weekdays'), ('1_month', '1 Month')], help_text='Schedule for this assignment (weekdays/weekend)', max_length=15, null=True),
        ),
    ]
