# Generated by Django 4.1.3 on 2025-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_trainercourse_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10),
        ),
    ]
