# Generated by Django 4.1.3 on 2025-09-19 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_attendance_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerWeeklyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='ISO week start (Monday)')),
                ('week_end', models.DateField(help_text='ISO week end (Sunday)')),
                ('classes_required', models.PositiveSmallIntegerField(default=3, help_text='3 for weekdays, 2 for weekend')),
                ('classes_held', models.PositiveSmallIntegerField(default=0)),
                ('force_open', models.BooleanField(default=False, help_text='Force the modal to open for trainer regardless of classes held')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_feedbacks', to='portal.trainer')),
                ('trainer_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_feedbacks', to='portal.trainercourse')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('trainer_course', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='TrainerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portal.trainerweeklyfeedback')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
