# Generated by Django 4.1.3 on 2025-07-01 13:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('duration', models.CharField(choices=[('1_month_weekdays', '1 Month Weekdays'), ('2_month_weekdays', '2 Month Weekdays'), ('3_month_weekends', '3 Month Weekends')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('lead_role', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=15, verbose_name='CNIC')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('second_installment', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField(blank=True, help_text='Due date for second installment', null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Unique invoice number for this student', max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='example.batch')),
                ('courses', models.ManyToManyField(related_name='students', to='example.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='example.csrprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_serial_number', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('school_name', models.CharField(default='Arfa Karim Technology Incubator Pvt Ltd ', max_length=255)),
                ('bank_name', models.CharField(default='JS Bank', max_length=100)),
                ('account_number', models.CharField(default='0002587773', max_length=50)),
                ('iban_number', models.CharField(default='PK56JSBL9561000002587773', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='example.csrprofile')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='example.csrprofile'),
        ),
    ]
