# Generated by Django 4.1.3 on 2025-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Name of CSR who enrolled the student (immutable)', max_length=100),
        ),
    ]
