# Generated by Django 4.1.3 on 2025-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_student_created_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='Comma-separated schedule/duration tags', max_length=100),
        ),
    ]
