# Generated by Django 4.1.3 on 2025-07-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedule',
            field=models.CharField(choices=[('weekdays', 'Weekdays'), ('weekend', 'Weekend'), ('1_month', '1 Month')], default='weekend', max_length=15),
        ),
    ]
