# Generated by Django 4.1.3 on 2025-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_student_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this batch has been completed'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this student is active'),
        ),
    ]
