# Generated by Django 4.1.3 on 2025-07-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_batch_is_completed_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
