# Generated by Django 4.1.3 on 2025-08-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_student_payment_method_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Batch status - inactive batches are considered completed', max_length=10),
        ),
    ]
