# Generated by Django 4.1.3 on 2025-08-08 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cnic',
            field=models.CharField(blank=True, help_text='CNIC or B-Form number', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online Payment')], default='cash', help_text='Payment method used by the student', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday')], default='weekend', max_length=15),
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_invoice_no', models.IntegerField(default=0, help_text='Regular invoice number, 0 means not yet generated')),
                ('pending_invoice_no', models.IntegerField(default=0, help_text='Pending payment invoice number, 0 means not yet generated')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_numbers', to='example.student')),
            ],
            options={
                'verbose_name': 'Student Invoice',
                'verbose_name_plural': 'Student Invoices',
            },
        ),
    ]
