# Generated by Django 4.1.3 on 2025-08-08 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_alter_student_cnic_alter_student_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advance_payment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount percentage', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='discounted_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday'), ('1_month', '1 Month')], default='weekend', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_installment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fees',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
