# Generated by Django 4.1.3 on 2025-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_alter_student_advance_payment_alter_student_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday'), ('weekdays', 'Weekdays'), ('1_month', '1 Month')], default='weekend', max_length=15),
        ),
    ]
