# Generated by Django 4.1.3 on 2025-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0013_alter_student_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekdays', 'Weekdays'), ('1_month', '1 Month')], default='weekend', max_length=15),
        ),
    ]
