# Generated by Django 4.1.3 on 2025-08-18 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0014_alter_student_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_amount',
            field=models.IntegerField(default=0, help_text='Total amount including advance payment and second installment', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
