# Generated by Django 4.1.3 on 2025-08-19 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0015_student_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.IntegerField(default=0, help_text='Balance amount to be paid', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
