# Generated by Django 4.1.3 on 2025-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0016_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_installment_due_date',
            field=models.DateField(blank=True, help_text='Due date for second installment payment', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date when pending invoice was generated', null=True),
        ),
    ]
