# Generated by Django 4.1.3 on 2025-08-24 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0017_student_second_installment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
