# Generated by Django 4.1.3 on 2026-02-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_student_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='school_name',
            field=models.CharField(default='Devinci Dev ', max_length=255),
        ),
    ]
