# Generated by Django 4.1.3 on 2026-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_alter_invoicesettings_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
